[build]
  publish = "dist"
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "22"

# Force HTTPS redirect
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200